import os
import json
import sys
import time
import re
from datetime import datetime
from ollama import Client
from prompt_toolkit import PromptSession
from prompt_toolkit.history import FileHistory
from prompt_toolkit.completion import WordCompleter

# Central imports
import config
from tools import AVAILABLE_TOOLS, AVAILABLE_FUNCTIONS
from preprocessor import preprocess_user_prompt, init_few_shot_db

REACT_SYSTEM_PROMPT = f"""
[CRITICAL SYSTEM DIRECTIVE]
You are Qwen, a highly capable AI agent built by Alibaba Cloud.
You suffer from artificial amnesia. You have ZERO internal knowledge about the real world, current events, or system metrics. 
You MUST use your provided tools to answer questions.

BEHAVIOR RULES:
1. Casual Greetings ("hello", "hi"): Reply directly without tools.
2. System Checks: DO NOT run system checks (cpu, mem, uptime) unless explicitly asked.
3. Factual Questions: You MUST call `search_ddg` or `search_wikipedia`. 
4. Math/Dates: You MUST call a calculation tool. 
5. Weather/Locations: You MUST call `get_weather`.
6. Multi-Source Research: You MUST call `web_research`, NOT `search_ddg` alone.

STRICT FORMATTING RULES:
- NEVER apologize.
- NEVER explain your thought process before calling a tool.
- NEVER output raw JSON text in your conversational response.
- Execute the native function calling API immediately when a tool is required.

SYSTEM TIME: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.
"""

def save_memory(msgs):
    with open(config.MEMORY_FILE, 'w') as f: json.dump(msgs, f, indent=2)

def extract_json_from_text(text: str) -> dict | None:
    """
    Scans a raw string for curly braces and attempts to extract the first 
    valid JSON dictionary that contains a "name" key, shedding any 
    unbalanced trailing characters generated by smaller models.
    """
    for m in re.finditer(r'\{', text):
        start = m.start()
        for end in range(len(text), start, -1):
            try:
                obj = json.loads(text[start:end])
                if isinstance(obj, dict) and "name" in obj:
                    return obj
            except json.JSONDecodeError:
                continue
    return None

def execute_react_loop(messages, verbose=False):
    for step in range(5):
        if not verbose: sys.stdout.write(f"\r\033[K💭 Thinking (Step {step+1})... ")
        
        response = config.client.chat(model=config.MODEL_NAME, messages=messages, tools=AVAILABLE_TOOLS, options={"num_ctx": config.OLLAMA_CTX, "temperature": 0.05})
        msg = response.message
        
        # --- Robust Sliding-Window Safety Net for JSON Tool Calls ---
        if not msg.tool_calls and msg.content:
            leaked_tool = extract_json_from_text(msg.content)
            if leaked_tool:
                class MockFunc:
                    def __init__(self, name, args): 
                        self.name = name
                        self.arguments = args
                class MockTool:
                    def __init__(self, func): 
                        self.function = func
                
                msg.tool_calls = [MockTool(MockFunc(leaked_tool["name"], leaked_tool.get("arguments", {})))]
                msg.content = ""
        # --------------------------------------------------------------------
        
        if verbose and msg.content: print(f"\n--- [Step {step+1}] ---\n{msg.content.strip()}\n-------------------------------")
        
        msg_dict = {"role": msg.role or "assistant", "content": msg.content or ""}
        
        # Restore standard tool appending for models with native tool support
        if msg.tool_calls:
            msg_dict["tool_calls"] = [{"function": {"name": tc.function.name, "arguments": tc.function.arguments}} for tc in msg.tool_calls]
            
        # SAFEGUARD: Do not append completely empty assistant turns to memory
        if msg_dict["content"].strip() or "tool_calls" in msg_dict:
            messages.append(msg_dict)
        else:
            fallback_text = "I encountered an empty response from the model. Please try again."
            messages.append({"role": "assistant", "content": fallback_text})
            msg.content = fallback_text  # Ensures it prints if everything fails
        
        if not msg.tool_calls:
            if not verbose: sys.stdout.write("\r\033[K")
            
            # --- Metrics parsing ---
            tps_text = ""
            try:
                eval_count = getattr(response, 'eval_count', 0) if hasattr(response, 'eval_count') else response.get('eval_count', 0)
                eval_duration = getattr(response, 'eval_duration', 0) if hasattr(response, 'eval_duration') else response.get('eval_duration', 0)
                
                if eval_count and eval_duration:
                    tps = (eval_count / eval_duration) * 1e9
                    tps_text = f" \033[90m({tps:.1f} tokens/s)\033[0m"
            except Exception:
                pass
                
            return (msg.content or "") + tps_text, messages
            
        for tool in msg.tool_calls:
            func_name = tool.function.name
            raw_args = tool.function.arguments
            
            func_args = {}
            if raw_args:
                for k, v in raw_args.items():
                    if isinstance(v, dict) and 'value' in v:
                        func_args[k] = v['value']
                    else:
                        func_args[k] = v
            
            if verbose: print(f"🛠  Executing: {func_name}({func_args})")
            else: sys.stdout.write(f"\r\033[K🛠  Running tool: {func_name}... ")
            
            try:
                obs = str(AVAILABLE_FUNCTIONS[func_name](**func_args))[:1500] if func_name in AVAILABLE_FUNCTIONS else f"Error: Tool '{func_name}' not found."
            except Exception as e:
                obs = f"Execution error in {func_name}: {e}"
                
            if verbose: print(f"👁  Observation loaded.\n")
            
            # Restore standard tool observation syntax
            messages.append({"role": "tool", "name": func_name, "content": obs})
            
    if not verbose: sys.stdout.write("\r\033[K")
    return "Error: Max iterations reached.", messages

def main():
    print("Connecting & Pulling Models...", flush=True)
    
    for i in range(30):  # Connection retry window
        try:
            # Ping the server to ensure it is awake
            config.client.list()
            
            # Only pull models if they do not already exist locally
            for model in [config.MODEL_NAME, config.SUB_MODEL_NAME, config.VISION_MODEL_NAME]:
                try:
                    config.client.show(model)
                except Exception:
                    config.client.pull(model)
            break
        except Exception as e:
            if i == 29: sys.exit(f"Ollama connection error: {e}")
            time.sleep(2)

    init_few_shot_db()
    messages = json.load(open(config.MEMORY_FILE)) if os.path.exists(config.MEMORY_FILE) else [{"role": "system", "content": REACT_SYSTEM_PROMPT}]
    verbose_mode = False
    
    os.system('cls' if os.name == 'nt' else 'clear')
    print(f"=== Agent Active ({config.MODEL_NAME}) ===\nTools loaded: {len(AVAILABLE_TOOLS)}\nCommands: /think, /wipe, /wipe_kb, /copy, exit\n")

    session = PromptSession(history=FileHistory(config.CMD_HISTORY_FILE))
    completer = WordCompleter(['/think', '/wipe', '/wipe_kb', '/copy', 'exit', 'quit'] + list(AVAILABLE_FUNCTIONS.keys()), ignore_case=True)
    last_response = ""

    while True:
        try:
            user_input = session.prompt("👤: ", completer=completer).strip()
            if not user_input: continue
            
            if (cmd := user_input.lower()) in ['exit', 'quit']:
                save_memory(messages); break
            if cmd == '/think':
                verbose_mode = not verbose_mode; print(f"🔧 Verbose mode: {'ON' if verbose_mode else 'OFF'}"); continue
            if cmd == '/wipe':
                messages = [{"role": "system", "content": REACT_SYSTEM_PROMPT}]; save_memory(messages); print("🧹 Memory wiped."); continue
            
            if cmd == '/wipe_kb':
                for coll_name in ["agent_knowledge", "agent_few_shot"]:
                    try: config.chroma_client.delete_collection(coll_name)
                    except Exception: pass
                
                try:
                    config.kb_collection = config.chroma_client.get_or_create_collection("agent_knowledge")
                    config.few_shot_collection = config.chroma_client.get_or_create_collection("agent_few_shot")
                    init_few_shot_db()
                    print("🧠 KB and Few-Shot databases wiped and reset.")
                except Exception as e: 
                    print(f"⚠️ Error recreating collections: {e}")
                continue
            
            if cmd == '/copy':
                config.copy_to_clipboard(last_response); print("📋 Copied!"); continue
            
            enriched_input = preprocess_user_prompt(user_input)
            if verbose_mode and enriched_input != user_input: print("✨ [Nomic Preprocessor Triggered]")

            messages.append({"role": "user", "content": enriched_input})
            last_response, messages = execute_react_loop(messages, verbose=verbose_mode)
            print(f"💻: {last_response}")
            save_memory(messages)

        except (KeyboardInterrupt, EOFError):
            save_memory(messages); break

if __name__ == "__main__":
    main()
